#!/bin/bash
echo "Since npm has permission issues, here's the manual deploy process:"
echo ""
echo "OPTION 1: Netlify Drop (Easiest - No account needed)"
echo "1. Open: https://app.netlify.com/drop"
echo "2. Drag this folder to the browser: ~/.openclaw/workspace/tenant-rep-site"
echo "3. Get instant public URL!"
echo ""
echo "OPTION 2: Vercel"  
echo "1. Go to: https://vercel.com"
echo "2. Sign up/login with GitHub"
echo "3. Import project → Upload folder"
echo "4. Select the tenant-rep-site folder"
echo ""
echo "OPTION 3: GitHub Pages (If you have GitHub)"
echo "1. Create new repo on github.com"
echo "2. Upload all files from tenant-rep-site" 
echo "3. Settings → Pages → Deploy from main branch"
echo ""
echo "The site files are ready at:"
echo "$(pwd)"